title: <p align="center"> Sathish Kumar Ramasamy</p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://in.linkedin.com/in/sathish-kumar-ramasamy/">LinkedIn</a> |
  <a href="https://github.com/SathishKumarRamasamy">GitHub</a>
  
  <br>   
  I'm currently working on IoT , Big data and has experience of about 7 years.
  <br>
  </p>



theme: jekyll-theme-minimal
